// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LambdaClient is the client API for Lambda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LambdaClient interface {
	StreamGetUserInfo(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error)
	StreamMqttCheck(ctx context.Context, in *MqttCheckRequest, opts ...grpc.CallOption) (*OperateResponse, error)
}

type lambdaClient struct {
	cc grpc.ClientConnInterface
}

func NewLambdaClient(cc grpc.ClientConnInterface) LambdaClient {
	return &lambdaClient{cc}
}

func (c *lambdaClient) StreamGetUserInfo(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error) {
	out := new(CheckUserResponse)
	err := c.cc.Invoke(ctx, "/api.ssmanager.grpc.lambda/StreamGetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lambdaClient) StreamMqttCheck(ctx context.Context, in *MqttCheckRequest, opts ...grpc.CallOption) (*OperateResponse, error) {
	out := new(OperateResponse)
	err := c.cc.Invoke(ctx, "/api.ssmanager.grpc.lambda/StreamMqttCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LambdaServer is the server API for Lambda service.
// All implementations must embed UnimplementedLambdaServer
// for forward compatibility
type LambdaServer interface {
	StreamGetUserInfo(context.Context, *CheckUserRequest) (*CheckUserResponse, error)
	StreamMqttCheck(context.Context, *MqttCheckRequest) (*OperateResponse, error)
	mustEmbedUnimplementedLambdaServer()
}

// UnimplementedLambdaServer must be embedded to have forward compatible implementations.
type UnimplementedLambdaServer struct {
}

func (UnimplementedLambdaServer) StreamGetUserInfo(context.Context, *CheckUserRequest) (*CheckUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamGetUserInfo not implemented")
}
func (UnimplementedLambdaServer) StreamMqttCheck(context.Context, *MqttCheckRequest) (*OperateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamMqttCheck not implemented")
}
func (UnimplementedLambdaServer) mustEmbedUnimplementedLambdaServer() {}

// UnsafeLambdaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LambdaServer will
// result in compilation errors.
type UnsafeLambdaServer interface {
	mustEmbedUnimplementedLambdaServer()
}

func RegisterLambdaServer(s grpc.ServiceRegistrar, srv LambdaServer) {
	s.RegisterService(&Lambda_ServiceDesc, srv)
}

func _Lambda_StreamGetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).StreamGetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ssmanager.grpc.lambda/StreamGetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).StreamGetUserInfo(ctx, req.(*CheckUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lambda_StreamMqttCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MqttCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServer).StreamMqttCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ssmanager.grpc.lambda/StreamMqttCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServer).StreamMqttCheck(ctx, req.(*MqttCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lambda_ServiceDesc is the grpc.ServiceDesc for Lambda service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lambda_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ssmanager.grpc.lambda",
	HandlerType: (*LambdaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamGetUserInfo",
			Handler:    _Lambda_StreamGetUserInfo_Handler,
		},
		{
			MethodName: "StreamMqttCheck",
			Handler:    _Lambda_StreamMqttCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aws-lambda.proto",
}
